language: python

sudo: false

python:
  - "3.6"

addons:
  apt:
    packages:
    - gfortran
    - libatlas-dev
    - libevent-dev
    - libfreetype6-dev
    - liblapack-dev
    - libpng12-dev
    - python-dev
    - python-tk

install:
  - pip -qqq install --upgrade pip setuptools
  - pip install pre-commit==1.12.0
  - pip -qqq install -r requirements.txt

cache: pip

env:
  global:
    - PYTHON_ENV=test
  matrix:
    - COMMAND="pre-commit run --all-files"
    - COMMAND="nosetests -v tests/"

script: $COMMAND

notifications:
  email: false
